In [1]:
import numpy as np
import torch

In [2]:
t = torch.tensor([[1,2,3],
                [4,5,6],
                 [7,8,9]] ,dtype=torch.float32)

print(t)
print()
print(f"Shape = {t.shape}")
print()

flat = t.flatten()

print(flat)
print(f"Shape = {flat.shape}")
print()

flat_start  = torch.flatten(t, start_dim=1)
print(flat_start)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Shape = torch.Size([3, 3])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape = torch.Size([9])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [3]:
trD = torch.tensor([[[1 ,2],
                     [3 ,4]],
                    
                    [[5 ,6],
                     [7 ,8]]])

print(trD)
print()
flat_start   =  torch.flatten(trD , start_dim=1) 

print(flat_start)
print(flat_start.shape)
print()

t_view =  flat_start.view(4,2)
print(t_view)

print()
print("View shapes memory")
print()
print(f"t_view[0,0] = {t_view[0, 0]}")
t_view[0,0] = 1334
print()

print(t_view)



tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

View shapes memory

t_view[0,0] = 1

tensor([[1334,    2],
        [   3,    4],
        [   5,    6],
        [   7,    8]])


In [4]:
t = torch.tensor([[[1,2,3]]] , dtype=torch.float32)

print("Original tensor ")
print()
print(f"shape : {t.shape}")
print()
t_squeezed = t.squeeze()

print("Squeezed (all size-1 dim removed) :")
print(t_squeezed)

Original tensor 

shape : torch.Size([1, 1, 3])

Squeezed (all size-1 dim removed) :
tensor([1., 2., 3.])


In [5]:
trD = torch.tensor([[[1 ,2],
                     [3 ,4]],
                    
                    [[5 ,6],
                     [7 ,8]]])

t_squeezed = trD.squeeze()

print("Squeezed (all size-1 dim removed) :")
print(t_squeezed)

Squeezed (all size-1 dim removed) :
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [14]:
zeros_1d = torch.zeros(5)
print(zeros_1d)
print()


zeros_2d = torch.zeros(3, 4)
print(zeros_2d)
print()

ones1d = torch.ones(5)
print(ones1d)
print()


ones2d = torch.ones(3, 4 )
print(ones2d)


full_tensor = torch.full((3, 5) , 6)
print(full_tensor)
print()



tensor([0., 0., 0., 0., 0.])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([1., 1., 1., 1., 1.])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]])



#CREATE TENSORS FRON NUMPY ARRAY

In [22]:
arr = np.array([1, 2, 3 , 5, 66,7])

print(arr)
print()


torch_tensor = torch.from_numpy(arr)
print(f"torch_tensor = {torch_tensor}")


tensor_back = torch.tensor([1,2,3,6,9,8,7])
to_arr = tensor_back.numpy()

print(to_arr)

[ 1  2  3  5 66  7]

torch_tensor = tensor([ 1,  2,  3,  5, 66,  7])
[1 2 3 6 9 8 7]


In [33]:
random_tensor  = torch.rand(3,4)

print(random_tensor)


random_int = torch.randint(0,10,(5,5))
print(random_int)


print()
print()
random_range = torch.randint(0,5,(3,3)) * 3
print(f"random_range = {random_range}")

tensor([[0.3708, 0.3775, 0.7797, 0.5636],
        [0.4977, 0.3069, 0.0982, 0.5410],
        [0.9953, 0.5133, 0.9281, 0.4241]])
tensor([[9, 5, 4, 6, 6],
        [7, 7, 1, 5, 0],
        [8, 0, 4, 5, 3],
        [8, 3, 5, 8, 6],
        [2, 8, 4, 8, 6]])


random_range = tensor([[ 9,  9,  0],
        [ 6,  9, 12],
        [ 0,  9, 12]])
