In [19]:
import numpy as np
import torch

In [39]:
t = torch.tensor([[1,2,3],
                [4,5,6],
                 [7,8,9]] ,dtype=torch.float32)

print(t)
print()
print(f"Shape = {t.shape}")
print()

flat = t.flatten()

print(flat)
print(f"Shape = {flat.shape}")
print()

flat_start  = torch.flatten(t, start_dim=1)
print(flat_start)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Shape = torch.Size([3, 3])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape = torch.Size([9])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [66]:
trD = torch.tensor([[[1 ,2],
                     [3 ,4]],
                    
                    [[5 ,6],
                     [7 ,8]]])

print(trD)
print()
flat_start   =  torch.flatten(trD , start_dim=1) 

print(flat_start)
print(flat_start.shape)
print()

t_view =  flat_start.view(4,2)
print(t_view)

print()
print("View shapes memory")
print()
print(f"t_view[0,0] = {t_view[0, 0]}")
t_view[0,0] = 1334
print()

print(t_view)



tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

View shapes memory

t_view[0,0] = 1

tensor([[1334,    2],
        [   3,    4],
        [   5,    6],
        [   7,    8]])


In [76]:
t = torch.tensor([[[1,2,3]]] , dtype=torch.float32)

print("Original tensor ")
print()
print(f"shape : {t.shape}")
print()
t_squeezed = t.squeeze()

print("Squeezed (all size-1 dim removed) :")
print(t_squeezed)

Original tensor 

shape : torch.Size([1, 1, 3])

Squeezed (all size-1 dim removed) :
tensor([1., 2., 3.])


In [77]:
trD = torch.tensor([[[1 ,2],
                     [3 ,4]],
                    
                    [[5 ,6],
                     [7 ,8]]])

t_squeezed = trD.squeeze()

print("Squeezed (all size-1 dim removed) :")
print(t_squeezed)

Squeezed (all size-1 dim removed) :
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
