In [4]:
import numpy as np
import torch 


A = torch.tensor([[1,2],
                 [3, 4]])


B = torch.tensor([[5, 6],
                 [7, 8]])


print("MATRIX A")
print(A)
print(A.shape)

print()



print("MATRIX B")
print(B)
print(B.shape)

MATRIX A
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])

MATRIX B
tensor([[5, 6],
        [7, 8]])
torch.Size([2, 2])


In [9]:
C = A@B


print("MATRIX C")
print(C)
print(C.shape)

      #using matmul


res2 = torch.matmul(A,B)
print("MATMUL ")

print(res2)

MATRIX C
tensor([[19, 22],
        [43, 50]])
torch.Size([2, 2])
MATMUL 
tensor([[19, 22],
        [43, 50]])


In [12]:
M = torch.tensor([[1,2],  [3, 4]])
v = torch.tensor([3,2])


mul = M@v
print(mul)

tensor([ 7, 17])
